[[redirects]]
  from = "/image/*"
  to = "/.netlify/functions/image/:splat"
  status = 200

[build]
  command = "npm install"
  publish = "admin"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["@napi-rs/canvas", "node-fetch"]
  included_files = ["node_modules/@napi-rs/**", "node_modules/node-fetch/**", "fonts/**"]
